// This file is autogenerated
use assets_helper::AssetsTrait;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum FileAssets {
    #[allow(dead_code)]
    FontsEditundoTtf,
    #[allow(dead_code)]
    ImagesGamePrimitivesRectPng,
    #[allow(dead_code)]
    ImagesGameGameBackgroundJpg,
    #[allow(dead_code)]
    ImagesGameMenuBackgroundJpg,
    #[allow(dead_code)]
    ImagesGameTilemapPackedPng,
    #[allow(dead_code)]
    ImagesGameUnitsTankPng,
    #[allow(dead_code)]
    ImagesGameUnitsAntiairPng,
    #[allow(dead_code)]
    ImagesGameUnitsApcPng,
    #[allow(dead_code)]
    ImagesGameUnitsArtilleryPng,
    #[allow(dead_code)]
    ImagesGameUnitsBattlecruiserPng,
    #[allow(dead_code)]
    ImagesGameUnitsBcopterPng,
    #[allow(dead_code)]
    ImagesGameUnitsBomberPng,
    #[allow(dead_code)]
    ImagesGameUnitsCarrierPng,
    #[allow(dead_code)]
    ImagesGameUnitsCruiserPng,
    #[allow(dead_code)]
    ImagesGameUnitsFighterPng,
    #[allow(dead_code)]
    ImagesGameUnitsInfantryPng,
    #[allow(dead_code)]
    ImagesGameUnitsLanderPng,
    #[allow(dead_code)]
    ImagesGameUnitsMaintankPng,
    #[allow(dead_code)]
    ImagesGameUnitsMechPng,
    #[allow(dead_code)]
    ImagesGameUnitsMissilePng,
    #[allow(dead_code)]
    ImagesGameUnitsReconPng,
    #[allow(dead_code)]
    ImagesGameUnitsRocketlauncherPng,
    #[allow(dead_code)]
    ImagesGameUnitsSubPng,
    #[allow(dead_code)]
    ImagesGameUnitsSupplyshipPng,
    #[allow(dead_code)]
    ImagesGameUnitsTcopterPng,
    #[allow(dead_code)]
    ImagesGameUnitsWartankPng,
    #[allow(dead_code)]
    ImagesGameTilemap2Png,
    #[allow(dead_code)]
    ImagesGameEffectsExplosionPng,
    #[allow(dead_code)]
    ImagesGameEffectsBombPng,
    #[allow(dead_code)]
    ImagesGameEffectsGunattackPng,
    #[allow(dead_code)]
    ImagesGameEffectsSmallExplosionPng,
    #[allow(dead_code)]
    ImagesGameEffectsTorpedoPng,
    #[allow(dead_code)]
    ImagesGameEffectsVulcanCannonPng,
    #[allow(dead_code)]
    ImagesGameCursorHud36X36Png,
    #[allow(dead_code)]
    ImagesGameCursorHud38X38Png,
    #[allow(dead_code)]
    ImagesGameCursorAttack40X40Png,
    #[allow(dead_code)]
    ImagesGameCursorAttack42X42Png,
    #[allow(dead_code)]
    ImagesGameMovementHudPng,
    #[allow(dead_code)]
    ImagesGameTerrainPng,
    #[allow(dead_code)]
    ImagesIconsNodesCarOutlineSvg,
    #[allow(dead_code)]
    ImagesIconsNodesFlagOutlineSvg,
    #[allow(dead_code)]
    ImagesIconsNodesLayersOutlineSvg,
    #[allow(dead_code)]
    ImagesIconsNodesPaperPlaneOutlineSvg,
    #[allow(dead_code)]
    ImagesIconsNodesPersonOutlineSvg,
    #[allow(dead_code)]
    ImagesIconsNodesSettings2OutlineSvg,
    #[allow(dead_code)]
    ImagesIconsNodesDownloadOutlineSvg,
    #[allow(dead_code)]
    ImagesIconsUiIconsDefaultPng,
    #[allow(dead_code)]
    ImagesIconsUiSheetBlack1XPng,
    #[allow(dead_code)]
    ImagesIconsUiSheetBlack2XPng,
    #[allow(dead_code)]
    ImagesIconsUiSheetWhite1XPng,
    #[allow(dead_code)]
    ImagesIconsUiSheetWhite2XPng,
    #[allow(dead_code)]
    ImagesThemeBlueSheetPng,
    #[allow(dead_code)]
    ImagesThemeCursorPng,
    #[allow(dead_code)]
    ImagesThemeGreenSheetPng,
    #[allow(dead_code)]
    ImagesThemeGreySheetPng,
    #[allow(dead_code)]
    ImagesThemeRedSheetPng,
    #[allow(dead_code)]
    ImagesThemeYellowSheetPng,
    #[allow(dead_code)]
    MusicsCyberpunkMoonlightSonataV2Mp3,
    #[allow(dead_code)]
    MusicsAwesomenessWav,
    #[allow(dead_code)]
    MusicsImmaculateCommandGeorgesDeMorgansThemeCodenameReconMp3,
    #[allow(dead_code)]
    MusicsTempestassAceInTheHoleMinatusLeonusMacrosThemeUnfinishedV08Mp3,
    #[allow(dead_code)]
    SoundsChipsHandle6Ogg,
    #[allow(dead_code)]
    SoundsEngineCircular000Ogg,
    #[allow(dead_code)]
    SoundsExplosionCrunch000Ogg,
    #[allow(dead_code)]
    SoundsExplosionCrunch004Ogg,
    #[allow(dead_code)]
    SoundsFootstepCarpet001Ogg,
    #[allow(dead_code)]
    SoundsHoldOgg,
    #[allow(dead_code)]
    SoundsImpactMining004Ogg,
    #[allow(dead_code)]
    SoundsImpactPlateMedium004Ogg,
    #[allow(dead_code)]
    SoundsLaserLarge004Ogg,
    #[allow(dead_code)]
    SoundsLaserRetro003Ogg,
    #[allow(dead_code)]
    SoundsLaserSmall001Ogg,
    #[allow(dead_code)]
    SoundsSpaceEngine001Ogg,
    #[allow(dead_code)]
    SoundsUiBack001Ogg,
    #[allow(dead_code)]
    SoundsUiBack002Ogg,
    #[allow(dead_code)]
    SoundsUiBack003Ogg,
    #[allow(dead_code)]
    SoundsUiBack004Ogg,
    #[allow(dead_code)]
    SoundsUiBong001Ogg,
    #[allow(dead_code)]
    SoundsUiClick001Ogg,
    #[allow(dead_code)]
    SoundsUiClick002Ogg,
    #[allow(dead_code)]
    SoundsUiClick003Ogg,
    #[allow(dead_code)]
    SoundsUiClick004Ogg,
    #[allow(dead_code)]
    SoundsUiClick005Ogg,
    #[allow(dead_code)]
    SoundsUiClose001Ogg,
    #[allow(dead_code)]
    SoundsUiClose002Ogg,
    #[allow(dead_code)]
    SoundsUiClose003Ogg,
    #[allow(dead_code)]
    SoundsUiClose004Ogg,
    #[allow(dead_code)]
    SoundsUiConfirmation001Ogg,
    #[allow(dead_code)]
    SoundsUiConfirmation002Ogg,
    #[allow(dead_code)]
    SoundsUiConfirmation003Ogg,
    #[allow(dead_code)]
    SoundsUiConfirmation004Ogg,
    #[allow(dead_code)]
    SoundsUiDoorOpen001Ogg,
    #[allow(dead_code)]
    SoundsUiDoorOpen002Ogg,
    #[allow(dead_code)]
    SoundsUiDrop001Ogg,
    #[allow(dead_code)]
    SoundsUiDrop002Ogg,
    #[allow(dead_code)]
    SoundsUiDrop003Ogg,
    #[allow(dead_code)]
    SoundsUiDrop004Ogg,
    #[allow(dead_code)]
    SoundsUiError001Ogg,
    #[allow(dead_code)]
    SoundsUiError002Ogg,
    #[allow(dead_code)]
    SoundsUiError003Ogg,
    #[allow(dead_code)]
    SoundsUiError004Ogg,
    #[allow(dead_code)]
    SoundsUiError005Ogg,
    #[allow(dead_code)]
    SoundsUiError006Ogg,
    #[allow(dead_code)]
    SoundsUiError007Ogg,
    #[allow(dead_code)]
    SoundsUiError008Ogg,
    #[allow(dead_code)]
    SoundsUiGlass001Ogg,
    #[allow(dead_code)]
    SoundsUiGlass002Ogg,
    #[allow(dead_code)]
    SoundsUiGlass003Ogg,
    #[allow(dead_code)]
    SoundsUiGlass004Ogg,
    #[allow(dead_code)]
    SoundsUiGlass005Ogg,
    #[allow(dead_code)]
    SoundsUiGlass006Ogg,
    #[allow(dead_code)]
    SoundsUiGlitch001Ogg,
    #[allow(dead_code)]
    SoundsUiGlitch002Ogg,
    #[allow(dead_code)]
    SoundsUiGlitch003Ogg,
    #[allow(dead_code)]
    SoundsUiGlitch004Ogg,
    #[allow(dead_code)]
    SoundsUiMaximize001Ogg,
    #[allow(dead_code)]
    SoundsUiMaximize002Ogg,
    #[allow(dead_code)]
    SoundsUiMaximize003Ogg,
    #[allow(dead_code)]
    SoundsUiMaximize004Ogg,
    #[allow(dead_code)]
    SoundsUiMaximize005Ogg,
    #[allow(dead_code)]
    SoundsUiMaximize006Ogg,
    #[allow(dead_code)]
    SoundsUiMaximize007Ogg,
    #[allow(dead_code)]
    SoundsUiMaximize008Ogg,
    #[allow(dead_code)]
    SoundsUiMaximize009Ogg,
    #[allow(dead_code)]
    SoundsUiMinimize001Ogg,
    #[allow(dead_code)]
    SoundsUiMinimize002Ogg,
    #[allow(dead_code)]
    SoundsUiMinimize003Ogg,
    #[allow(dead_code)]
    SoundsUiMinimize004Ogg,
    #[allow(dead_code)]
    SoundsUiMinimize005Ogg,
    #[allow(dead_code)]
    SoundsUiMinimize006Ogg,
    #[allow(dead_code)]
    SoundsUiMinimize007Ogg,
    #[allow(dead_code)]
    SoundsUiMinimize008Ogg,
    #[allow(dead_code)]
    SoundsUiMinimize009Ogg,
    #[allow(dead_code)]
    SoundsUiOpen001Ogg,
    #[allow(dead_code)]
    SoundsUiOpen002Ogg,
    #[allow(dead_code)]
    SoundsUiOpen003Ogg,
    #[allow(dead_code)]
    SoundsUiOpen004Ogg,
    #[allow(dead_code)]
    SoundsUiPluck001Ogg,
    #[allow(dead_code)]
    SoundsUiPluck002Ogg,
    #[allow(dead_code)]
    SoundsUiQuestion001Ogg,
    #[allow(dead_code)]
    SoundsUiQuestion002Ogg,
    #[allow(dead_code)]
    SoundsUiQuestion003Ogg,
    #[allow(dead_code)]
    SoundsUiQuestion004Ogg,
    #[allow(dead_code)]
    SoundsUiScratch001Ogg,
    #[allow(dead_code)]
    SoundsUiScratch002Ogg,
    #[allow(dead_code)]
    SoundsUiScratch003Ogg,
    #[allow(dead_code)]
    SoundsUiScratch004Ogg,
    #[allow(dead_code)]
    SoundsUiScratch005Ogg,
    #[allow(dead_code)]
    SoundsUiScroll001Ogg,
    #[allow(dead_code)]
    SoundsUiScroll002Ogg,
    #[allow(dead_code)]
    SoundsUiScroll003Ogg,
    #[allow(dead_code)]
    SoundsUiScroll004Ogg,
    #[allow(dead_code)]
    SoundsUiScroll005Ogg,
    #[allow(dead_code)]
    SoundsUiSelect001Ogg,
    #[allow(dead_code)]
    SoundsUiSelect002Ogg,
    #[allow(dead_code)]
    SoundsUiSelect003Ogg,
    #[allow(dead_code)]
    SoundsUiSelect004Ogg,
    #[allow(dead_code)]
    SoundsUiSelect005Ogg,
    #[allow(dead_code)]
    SoundsUiSelect006Ogg,
    #[allow(dead_code)]
    SoundsUiSelect007Ogg,
    #[allow(dead_code)]
    SoundsUiSelect008Ogg,
    #[allow(dead_code)]
    SoundsUiSwitch001Ogg,
    #[allow(dead_code)]
    SoundsUiSwitch002Ogg,
    #[allow(dead_code)]
    SoundsUiSwitch003Ogg,
    #[allow(dead_code)]
    SoundsUiSwitch004Ogg,
    #[allow(dead_code)]
    SoundsUiSwitch005Ogg,
    #[allow(dead_code)]
    SoundsUiSwitch006Ogg,
    #[allow(dead_code)]
    SoundsUiSwitch007Ogg,
    #[allow(dead_code)]
    SoundsUiTick001Ogg,
    #[allow(dead_code)]
    SoundsUiTick002Ogg,
    #[allow(dead_code)]
    SoundsUiTick004Ogg,
    #[allow(dead_code)]
    SoundsUiToggle001Ogg,
    #[allow(dead_code)]
    SoundsUiToggle002Ogg,
    #[allow(dead_code)]
    SoundsUiToggle003Ogg,
    #[allow(dead_code)]
    SoundsUiToggle004Ogg,
    #[allow(dead_code)]
    TextCreditsMd,
    #[allow(dead_code)]
    MenuStyleUiCss,
    #[allow(dead_code)]
    MenuStyleMenuCss,
    #[allow(dead_code)]
    MapTestAbwm,
    #[allow(dead_code)]
    CommandersBaseAbwc,
}

impl AssetsTrait for FileAssets {
    fn path(&self) -> &'static str {
        match self {
            FileAssets::FontsEditundoTtf => "fonts/editundo.ttf",
            FileAssets::ImagesGamePrimitivesRectPng => "images/game/primitives/rect.png",
            FileAssets::ImagesGameGameBackgroundJpg => "images/game/game/background.jpg",
            FileAssets::ImagesGameMenuBackgroundJpg => "images/game/menu/background.jpg",
            FileAssets::ImagesGameTilemapPackedPng => "images/game/tilemap_packed.png",
            FileAssets::ImagesGameUnitsTankPng => "images/game/units/tank.png",
            FileAssets::ImagesGameUnitsAntiairPng => "images/game/units/antiair.png",
            FileAssets::ImagesGameUnitsApcPng => "images/game/units/apc.png",
            FileAssets::ImagesGameUnitsArtilleryPng => "images/game/units/artillery.png",
            FileAssets::ImagesGameUnitsBattlecruiserPng => "images/game/units/battlecruiser.png",
            FileAssets::ImagesGameUnitsBcopterPng => "images/game/units/bcopter.png",
            FileAssets::ImagesGameUnitsBomberPng => "images/game/units/bomber.png",
            FileAssets::ImagesGameUnitsCarrierPng => "images/game/units/carrier.png",
            FileAssets::ImagesGameUnitsCruiserPng => "images/game/units/cruiser.png",
            FileAssets::ImagesGameUnitsFighterPng => "images/game/units/fighter.png",
            FileAssets::ImagesGameUnitsInfantryPng => "images/game/units/infantry.png",
            FileAssets::ImagesGameUnitsLanderPng => "images/game/units/lander.png",
            FileAssets::ImagesGameUnitsMaintankPng => "images/game/units/maintank.png",
            FileAssets::ImagesGameUnitsMechPng => "images/game/units/mech.png",
            FileAssets::ImagesGameUnitsMissilePng => "images/game/units/missile.png",
            FileAssets::ImagesGameUnitsReconPng => "images/game/units/recon.png",
            FileAssets::ImagesGameUnitsRocketlauncherPng => "images/game/units/rocketlauncher.png",
            FileAssets::ImagesGameUnitsSubPng => "images/game/units/sub.png",
            FileAssets::ImagesGameUnitsSupplyshipPng => "images/game/units/supplyship.png",
            FileAssets::ImagesGameUnitsTcopterPng => "images/game/units/tcopter.png",
            FileAssets::ImagesGameUnitsWartankPng => "images/game/units/wartank.png",
            FileAssets::ImagesGameTilemap2Png => "images/game/tilemap2.png",
            FileAssets::ImagesGameEffectsExplosionPng => "images/game/effects/explosion.png",
            FileAssets::ImagesGameEffectsBombPng => "images/game/effects/bomb.png",
            FileAssets::ImagesGameEffectsGunattackPng => "images/game/effects/gunattack.png",
            FileAssets::ImagesGameEffectsSmallExplosionPng => "images/game/effects/small_explosion.png",
            FileAssets::ImagesGameEffectsTorpedoPng => "images/game/effects/torpedo.png",
            FileAssets::ImagesGameEffectsVulcanCannonPng => "images/game/effects/vulcan_cannon.png",
            FileAssets::ImagesGameCursorHud36X36Png => "images/game/cursor hud 36x36.png",
            FileAssets::ImagesGameCursorHud38X38Png => "images/game/cursor hud 38x38.png",
            FileAssets::ImagesGameCursorAttack40X40Png => "images/game/cursor_attack_40x40.png",
            FileAssets::ImagesGameCursorAttack42X42Png => "images/game/cursor_attack_42x42.png",
            FileAssets::ImagesGameMovementHudPng => "images/game/movement hud.png",
            FileAssets::ImagesGameTerrainPng => "images/game/terrain.png",
            FileAssets::ImagesIconsNodesCarOutlineSvg => "images/icons/nodes/car-outline.svg",
            FileAssets::ImagesIconsNodesFlagOutlineSvg => "images/icons/nodes/flag-outline.svg",
            FileAssets::ImagesIconsNodesLayersOutlineSvg => "images/icons/nodes/layers-outline.svg",
            FileAssets::ImagesIconsNodesPaperPlaneOutlineSvg => "images/icons/nodes/paper-plane-outline.svg",
            FileAssets::ImagesIconsNodesPersonOutlineSvg => "images/icons/nodes/person-outline.svg",
            FileAssets::ImagesIconsNodesSettings2OutlineSvg => "images/icons/nodes/settings-2-outline.svg",
            FileAssets::ImagesIconsNodesDownloadOutlineSvg => "images/icons/nodes/download-outline.svg",
            FileAssets::ImagesIconsUiIconsDefaultPng => "images/icons/ui/iconsDefault.png",
            FileAssets::ImagesIconsUiSheetBlack1XPng => "images/icons/ui/sheet_black1x.png",
            FileAssets::ImagesIconsUiSheetBlack2XPng => "images/icons/ui/sheet_black2x.png",
            FileAssets::ImagesIconsUiSheetWhite1XPng => "images/icons/ui/sheet_white1x.png",
            FileAssets::ImagesIconsUiSheetWhite2XPng => "images/icons/ui/sheet_white2x.png",
            FileAssets::ImagesThemeBlueSheetPng => "images/theme/blueSheet.png",
            FileAssets::ImagesThemeCursorPng => "images/theme/cursor.png",
            FileAssets::ImagesThemeGreenSheetPng => "images/theme/greenSheet.png",
            FileAssets::ImagesThemeGreySheetPng => "images/theme/greySheet.png",
            FileAssets::ImagesThemeRedSheetPng => "images/theme/redSheet.png",
            FileAssets::ImagesThemeYellowSheetPng => "images/theme/yellowSheet.png",
            FileAssets::MusicsCyberpunkMoonlightSonataV2Mp3 => "musics/Cyberpunk Moonlight Sonata v2.mp3",
            FileAssets::MusicsAwesomenessWav => "musics/awesomeness.wav",
            FileAssets::MusicsImmaculateCommandGeorgesDeMorgansThemeCodenameReconMp3 => "musics/Immaculate_Command__Georges_DeMorgans_Theme_Codename_RECON.mp3",
            FileAssets::MusicsTempestassAceInTheHoleMinatusLeonusMacrosThemeUnfinishedV08Mp3 => "musics/Tempestass_Ace_in_the_Hole__Minatus_Leonus_Macros_Theme_UNFINISHED_v0.8.mp3",
            FileAssets::SoundsChipsHandle6Ogg => "sounds/chipsHandle6.ogg",
            FileAssets::SoundsEngineCircular000Ogg => "sounds/engineCircular_000.ogg",
            FileAssets::SoundsExplosionCrunch000Ogg => "sounds/explosionCrunch_000.ogg",
            FileAssets::SoundsExplosionCrunch004Ogg => "sounds/explosionCrunch_004.ogg",
            FileAssets::SoundsFootstepCarpet001Ogg => "sounds/footstep_carpet_001.ogg",
            FileAssets::SoundsHoldOgg => "sounds/hold.ogg",
            FileAssets::SoundsImpactMining004Ogg => "sounds/impactMining_004.ogg",
            FileAssets::SoundsImpactPlateMedium004Ogg => "sounds/impactPlate_medium_004.ogg",
            FileAssets::SoundsLaserLarge004Ogg => "sounds/laserLarge_004.ogg",
            FileAssets::SoundsLaserRetro003Ogg => "sounds/laserRetro_003.ogg",
            FileAssets::SoundsLaserSmall001Ogg => "sounds/laserSmall_001.ogg",
            FileAssets::SoundsSpaceEngine001Ogg => "sounds/spaceEngine_001.ogg",
            FileAssets::SoundsUiBack001Ogg => "sounds/ui/back_001.ogg",
            FileAssets::SoundsUiBack002Ogg => "sounds/ui/back_002.ogg",
            FileAssets::SoundsUiBack003Ogg => "sounds/ui/back_003.ogg",
            FileAssets::SoundsUiBack004Ogg => "sounds/ui/back_004.ogg",
            FileAssets::SoundsUiBong001Ogg => "sounds/ui/bong_001.ogg",
            FileAssets::SoundsUiClick001Ogg => "sounds/ui/click_001.ogg",
            FileAssets::SoundsUiClick002Ogg => "sounds/ui/click_002.ogg",
            FileAssets::SoundsUiClick003Ogg => "sounds/ui/click_003.ogg",
            FileAssets::SoundsUiClick004Ogg => "sounds/ui/click_004.ogg",
            FileAssets::SoundsUiClick005Ogg => "sounds/ui/click_005.ogg",
            FileAssets::SoundsUiClose001Ogg => "sounds/ui/close_001.ogg",
            FileAssets::SoundsUiClose002Ogg => "sounds/ui/close_002.ogg",
            FileAssets::SoundsUiClose003Ogg => "sounds/ui/close_003.ogg",
            FileAssets::SoundsUiClose004Ogg => "sounds/ui/close_004.ogg",
            FileAssets::SoundsUiConfirmation001Ogg => "sounds/ui/confirmation_001.ogg",
            FileAssets::SoundsUiConfirmation002Ogg => "sounds/ui/confirmation_002.ogg",
            FileAssets::SoundsUiConfirmation003Ogg => "sounds/ui/confirmation_003.ogg",
            FileAssets::SoundsUiConfirmation004Ogg => "sounds/ui/confirmation_004.ogg",
            FileAssets::SoundsUiDoorOpen001Ogg => "sounds/ui/doorOpen_001.ogg",
            FileAssets::SoundsUiDoorOpen002Ogg => "sounds/ui/doorOpen_002.ogg",
            FileAssets::SoundsUiDrop001Ogg => "sounds/ui/drop_001.ogg",
            FileAssets::SoundsUiDrop002Ogg => "sounds/ui/drop_002.ogg",
            FileAssets::SoundsUiDrop003Ogg => "sounds/ui/drop_003.ogg",
            FileAssets::SoundsUiDrop004Ogg => "sounds/ui/drop_004.ogg",
            FileAssets::SoundsUiError001Ogg => "sounds/ui/error_001.ogg",
            FileAssets::SoundsUiError002Ogg => "sounds/ui/error_002.ogg",
            FileAssets::SoundsUiError003Ogg => "sounds/ui/error_003.ogg",
            FileAssets::SoundsUiError004Ogg => "sounds/ui/error_004.ogg",
            FileAssets::SoundsUiError005Ogg => "sounds/ui/error_005.ogg",
            FileAssets::SoundsUiError006Ogg => "sounds/ui/error_006.ogg",
            FileAssets::SoundsUiError007Ogg => "sounds/ui/error_007.ogg",
            FileAssets::SoundsUiError008Ogg => "sounds/ui/error_008.ogg",
            FileAssets::SoundsUiGlass001Ogg => "sounds/ui/glass_001.ogg",
            FileAssets::SoundsUiGlass002Ogg => "sounds/ui/glass_002.ogg",
            FileAssets::SoundsUiGlass003Ogg => "sounds/ui/glass_003.ogg",
            FileAssets::SoundsUiGlass004Ogg => "sounds/ui/glass_004.ogg",
            FileAssets::SoundsUiGlass005Ogg => "sounds/ui/glass_005.ogg",
            FileAssets::SoundsUiGlass006Ogg => "sounds/ui/glass_006.ogg",
            FileAssets::SoundsUiGlitch001Ogg => "sounds/ui/glitch_001.ogg",
            FileAssets::SoundsUiGlitch002Ogg => "sounds/ui/glitch_002.ogg",
            FileAssets::SoundsUiGlitch003Ogg => "sounds/ui/glitch_003.ogg",
            FileAssets::SoundsUiGlitch004Ogg => "sounds/ui/glitch_004.ogg",
            FileAssets::SoundsUiMaximize001Ogg => "sounds/ui/maximize_001.ogg",
            FileAssets::SoundsUiMaximize002Ogg => "sounds/ui/maximize_002.ogg",
            FileAssets::SoundsUiMaximize003Ogg => "sounds/ui/maximize_003.ogg",
            FileAssets::SoundsUiMaximize004Ogg => "sounds/ui/maximize_004.ogg",
            FileAssets::SoundsUiMaximize005Ogg => "sounds/ui/maximize_005.ogg",
            FileAssets::SoundsUiMaximize006Ogg => "sounds/ui/maximize_006.ogg",
            FileAssets::SoundsUiMaximize007Ogg => "sounds/ui/maximize_007.ogg",
            FileAssets::SoundsUiMaximize008Ogg => "sounds/ui/maximize_008.ogg",
            FileAssets::SoundsUiMaximize009Ogg => "sounds/ui/maximize_009.ogg",
            FileAssets::SoundsUiMinimize001Ogg => "sounds/ui/minimize_001.ogg",
            FileAssets::SoundsUiMinimize002Ogg => "sounds/ui/minimize_002.ogg",
            FileAssets::SoundsUiMinimize003Ogg => "sounds/ui/minimize_003.ogg",
            FileAssets::SoundsUiMinimize004Ogg => "sounds/ui/minimize_004.ogg",
            FileAssets::SoundsUiMinimize005Ogg => "sounds/ui/minimize_005.ogg",
            FileAssets::SoundsUiMinimize006Ogg => "sounds/ui/minimize_006.ogg",
            FileAssets::SoundsUiMinimize007Ogg => "sounds/ui/minimize_007.ogg",
            FileAssets::SoundsUiMinimize008Ogg => "sounds/ui/minimize_008.ogg",
            FileAssets::SoundsUiMinimize009Ogg => "sounds/ui/minimize_009.ogg",
            FileAssets::SoundsUiOpen001Ogg => "sounds/ui/open_001.ogg",
            FileAssets::SoundsUiOpen002Ogg => "sounds/ui/open_002.ogg",
            FileAssets::SoundsUiOpen003Ogg => "sounds/ui/open_003.ogg",
            FileAssets::SoundsUiOpen004Ogg => "sounds/ui/open_004.ogg",
            FileAssets::SoundsUiPluck001Ogg => "sounds/ui/pluck_001.ogg",
            FileAssets::SoundsUiPluck002Ogg => "sounds/ui/pluck_002.ogg",
            FileAssets::SoundsUiQuestion001Ogg => "sounds/ui/question_001.ogg",
            FileAssets::SoundsUiQuestion002Ogg => "sounds/ui/question_002.ogg",
            FileAssets::SoundsUiQuestion003Ogg => "sounds/ui/question_003.ogg",
            FileAssets::SoundsUiQuestion004Ogg => "sounds/ui/question_004.ogg",
            FileAssets::SoundsUiScratch001Ogg => "sounds/ui/scratch_001.ogg",
            FileAssets::SoundsUiScratch002Ogg => "sounds/ui/scratch_002.ogg",
            FileAssets::SoundsUiScratch003Ogg => "sounds/ui/scratch_003.ogg",
            FileAssets::SoundsUiScratch004Ogg => "sounds/ui/scratch_004.ogg",
            FileAssets::SoundsUiScratch005Ogg => "sounds/ui/scratch_005.ogg",
            FileAssets::SoundsUiScroll001Ogg => "sounds/ui/scroll_001.ogg",
            FileAssets::SoundsUiScroll002Ogg => "sounds/ui/scroll_002.ogg",
            FileAssets::SoundsUiScroll003Ogg => "sounds/ui/scroll_003.ogg",
            FileAssets::SoundsUiScroll004Ogg => "sounds/ui/scroll_004.ogg",
            FileAssets::SoundsUiScroll005Ogg => "sounds/ui/scroll_005.ogg",
            FileAssets::SoundsUiSelect001Ogg => "sounds/ui/select_001.ogg",
            FileAssets::SoundsUiSelect002Ogg => "sounds/ui/select_002.ogg",
            FileAssets::SoundsUiSelect003Ogg => "sounds/ui/select_003.ogg",
            FileAssets::SoundsUiSelect004Ogg => "sounds/ui/select_004.ogg",
            FileAssets::SoundsUiSelect005Ogg => "sounds/ui/select_005.ogg",
            FileAssets::SoundsUiSelect006Ogg => "sounds/ui/select_006.ogg",
            FileAssets::SoundsUiSelect007Ogg => "sounds/ui/select_007.ogg",
            FileAssets::SoundsUiSelect008Ogg => "sounds/ui/select_008.ogg",
            FileAssets::SoundsUiSwitch001Ogg => "sounds/ui/switch_001.ogg",
            FileAssets::SoundsUiSwitch002Ogg => "sounds/ui/switch_002.ogg",
            FileAssets::SoundsUiSwitch003Ogg => "sounds/ui/switch_003.ogg",
            FileAssets::SoundsUiSwitch004Ogg => "sounds/ui/switch_004.ogg",
            FileAssets::SoundsUiSwitch005Ogg => "sounds/ui/switch_005.ogg",
            FileAssets::SoundsUiSwitch006Ogg => "sounds/ui/switch_006.ogg",
            FileAssets::SoundsUiSwitch007Ogg => "sounds/ui/switch_007.ogg",
            FileAssets::SoundsUiTick001Ogg => "sounds/ui/tick_001.ogg",
            FileAssets::SoundsUiTick002Ogg => "sounds/ui/tick_002.ogg",
            FileAssets::SoundsUiTick004Ogg => "sounds/ui/tick_004.ogg",
            FileAssets::SoundsUiToggle001Ogg => "sounds/ui/toggle_001.ogg",
            FileAssets::SoundsUiToggle002Ogg => "sounds/ui/toggle_002.ogg",
            FileAssets::SoundsUiToggle003Ogg => "sounds/ui/toggle_003.ogg",
            FileAssets::SoundsUiToggle004Ogg => "sounds/ui/toggle_004.ogg",
            FileAssets::TextCreditsMd => "text/credits.md",
            FileAssets::MenuStyleUiCss => "menu_style/ui.css",
            FileAssets::MenuStyleMenuCss => "menu_style/menu.css",
            FileAssets::MapTestAbwm => "map_test.abwm",
            FileAssets::CommandersBaseAbwc => "commanders/base.abwc",
        }
    }
}
